mavenGitflowPipeline {

    /***************************************************************************
    * Sonar GitHub Credentials - Settings this value will configure the pipeline 
    * to use this credential to connect to GitHub during sonar PR scans, adding 
    * comments for any violations found
    *************************************************************************/
    // sonarGithubCredentials = 'dsva-github'

    /***************************************************************************
    * GitHub credential ID to use for releases
    *************************************************************************/
    // githubCredentials = 'epmo-github'

    /*************************************************************************
    * Docker Build Configuration
    *************************************************************************/

    // Map of Image Names to sub-directory in the repository. If this is value is non-empty, 
    // the build pipeline will build all images specified in the map. The example below will build an image tagged as 
    // `bip-origin:latest` using the Docker context of `./bip-origin`.
    dockerBuilds = [
        'bip-origin': 'bip-origin'
    ]

    /*************************************************************************
    * Functional Testing Configuration
    *************************************************************************/

    //Additional Mavn options to use when running functional test cases
    cucumberOpts = "--tags @DEV"

    /*************************************************************************
    * OpenShift Deployment Configuration
    *
    * This section only applied to builds running on the OpenShift platform.
    * This section should be omitted if you are using Helm for deployments on
    * Kubernetes.
    *************************************************************************/
    //Path to your applications OpenShift deployment template
    deploymentTemplates = ["template.yaml"]
    
    //Deployment parameters used to configure your OpenShift deployment template
    deploymentParameters = [
        'APP_NAME': 'bip-origin',
        'IMAGE': 'bip-origin'
    ]

    /*************************************************************************
    * Helm Deployment Configuration
    *
    * This section only applied to builds running on the Kubernetes platform.
    * This section should be omitted if you are using OpenShift templates for
    * deployment on OpenShift.
    *************************************************************************/

    //Git Repository that contains your Helm chart
    chartRepository = "https://github.ec.va.gov/EPMO/bip-external-config"

    //Path to your chart directory within the above repository
    chartPath = "charts/bip-origin"

    //Jenkins credential ID to use when connecting to repository. This defaults to `github` if not specified
    chartCredentialId = "github"

    //Value YAML file used to configure the Helm deployments used for functional and performance testing.
    chartValueFile = "testing.yaml"

    //Release name to use
    chartReleaseName = "bip-origin"
}