package gov.va.bip.origin.transform.impl;

/**
 * Transform a service Domain request object to a Partner client request object.
 * Partner data classes are typically generated by XJC, Swagger CodeGen or similar
 * from the WSDL or XSD provided by the partner.
 */
public class SampleByPidDomainToPartner {
	/* as shown below, domain-to-partner transform classes must extend AbstractDomainToPartner */
	// extends AbstractDomainToPartner<SomeDomainRequest, SomePartnerReqeust> {

	/**
	 * Transform a service Domain request object into a Partner client request object.
	 * <p>
	 * {@inheritDoc AbstractDomainToPartner}
	 */
//	@Override
//	public SomePartnerReqeust convert(SomeDomainRequest domainObject) {
//		SomePartnerReqeust partnerObject = new SomePartnerReqeust();
//		if (domainObject != null) {
//			partnerObject.setSomeValue(domainObject.getSomeValue());
//		}
//		return partnerObject;
//	}
}
